### ISSUE TITLE
Level's mixed up.

### ISSUE THREAD

**Issue by TheFatalKiller** [fourjr/rainbot#2]
so level 5 which should only have bypassing auto moderation also has the permission to mute, unmute etc(when only level 6 should have the permission to). and perm level 6 which should be able to by pass moderation and only have access to mute/unmute but also has access to ban command which should only be level 7.

**Comment by fourjr** [comment]
You can use `!!setcommandlevel` for this.

We are now public. Invite: https://discord.com/oauth2/authorize?client_id=372748944448552961&scope=bot&permissions=2013621494
