### ISSUE TITLE
Mute bypass

### ISSUE THREAD

**Issue by TheFatalKiller** [fourjr/rainbot#7]
Can you make it so if someone is muted, if they leave and rejoin they’re still muted for the same amount of time, because I don’t want people to bypass. Because at the moment if you leave and rejoin you can talk again.

**Comment by SharpBit** [comment]
at that point just ban them from the server for bypassing a mute

**Comment by TheFatalKiller** [comment]
Still it needs to be fixed.

**Comment by fourjr** [comment]
Resolved
